// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcs

import (
	"time"
)

type Account struct {
	ID          int64
	Owner       string
	Balance     int64
	Currency    string
	CreatedAt   time.Time
	CountryCode int32
}

type Entry struct {
	ID        int64
	AccountID int64
	// this can be negative or positive
	Ammount   int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// this should always be positive
	Ammount   int64
	CreatedAt time.Time
}

type User struct {
	Username          string
	Hashedpassword    string
	FullName          string
	Email             string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
}
